pack_project = {'AXIdentifier': 'ID_MENU_FILE_PACK_PROJ_MATERIAL_TO_LIVE'}
save_project = {'AXIdentifier': 'ID_MENU_FILE_SAVE_PROJECT_TO_LIVE'}
upload_dialog = {'AXIdentifier': 'IDC_UPLOAD_PROJECT_DLG'}
projectname = {'AXIdentifier': 'IDC_UPLOAD_PROJECT_PROJECTNAME'}
btn_ok = {'AXIdentifier': 'IDC_UPLOAD_PROJECT_OK'}
btn_cancel = {'AXIdentifier': 'IDC_UPLOAD_PROJECT_CANCEL'}
btn_close = {'AXSubrole': 'AXCloseButton', 'AXRole': 'AXButton'}
btn_warning_ok = {'AXIdentifier': 'IDC_CLALERT_BUTTON_0'}
btn_uploading_cancel = {'AXIdentifier': 'IDC_CLOUDPROGRESS_PROGRESS_BTN_CANCEL'}
btn_uploading_cancel_yes = {'AXIdentifier': 'IDC_CLALERT_BUTTON_0'}
upload_template_dialog = {'AXIdentifier': 'IDC_UPLOAD_TEMPLATE_FROM_CYBERLINKCLOUD_DLG'}
upload_to = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_HOWLOADTO'}
upload_to_both = {'AXRole': 'AXStaticText', 'AXValue':'CyberLink Cloud and DirectorZone'}
upload_to_cl = {'AXRole': 'AXStaticText', 'AXValue':'CyberLink Cloud'}
upload_to_dz = {'AXRole': 'AXStaticText', 'AXValue':'DirectorZone'}
used_space = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_DETAIL_USED_SPACE'} #3310 _NS:409
used_space_detail = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_DETAIL_SETUPPAGE'}
upload_title = {'AXIdentifier': 'IDS_UPLOAD_TEMPLATE_LABEL_TITLE'} #3310 _NS:96
upload_style = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_STYLE'}
upload_tags = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_TAGS'}
upload_collection = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_COLLECTION'}
upload_description = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_DESCRIPTION'}
upload_btn_next = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_NEXT'}
upload_btn_cancel = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_CANCEL'}
upload_btn_finish = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_FINISH'}
upload_btn_previous = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_PREVIOUS'}
upload_tick_confirm = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_CONFIRM'}
upload_view_DZ = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_DZ_UPLOADTEMPLATE'}
upload_view_CL = {'AXIdentifier': 'IDC_UPLOADTEMPLATE_CLOUD_UPLOADTEMPLATE'}
alert_message_replace = {'AXIdentifier': 'IDC_CLALERT_MESSAGE', 'AXValue': 'The project already exists on CyberLink Cloud. Do you want to overwrite it?'}
upload_project_preview = {'AXIdentifier': 'IDC_UPLOAD_PROJECT_PREVIEW'}

