btn_device = {'AXIdentifier': 'IDC_VOICEOVER_BTN_DEVICE', 'AXRole': 'AXButton'}
txt_audio_detect = {'AXIdentifier': '_NS:39'} #20v3310_Checked. the detected audio device name
btn_record = {'AXIdentifier': 'IDC_VOICEOVER_BTN_RECORD', 'AXRole': 'AXButton'}
btn_audio_setup_ok = {'AXIdentifier': 'IDC_AUDIO_SETUP_BTN_OK', 'AXRole': 'AXButton'}
window_audio_setup = {'AXIdentifier': 'IDD_AUDIO_SETUP', 'AXRole': 'AXWindow'}
btn_audio_setup_close = {'AXRole': 'AXButton', 'AXRoleDescription': 'close button'}
chx_timelimit = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_TIME_LIMIT', 'AXTitle': 'Time limit'}
btn_preference = {'AXIdentifier': 'IDC_VOICEOVER_BTN_OPTIONS', 'AXRole': 'AXButton'}
window_recording_preference = {'AXIdentifier': 'IDD_VOICEOVER_OPTIONS', 'AXTitle': 'Recording Preferences'}
cbx_hour = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_COMBOBOX_HOUR', 'AXRole': 'AXButton'}
chx_delay_3s = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_DELAY_PLAY', 'AXTitle': 'Add a 3 second delay before recording'}
chx_auto_fade_in = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_FADE_IN', 'AXTitle': 'Auto fade-in at beginning of recording'}
chx_auto_fade_out = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_FADE_OUT', 'AXTitle': 'Auto fade-out at end of recording'}
btn_recording_preferences_ok = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_OK', 'AXRole': 'AXButton'}
btn_recording_preferences_cancel = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_BTN_CANCEL', 'AXRole': 'AXButton'}
btn_record = {'AXIdentifier': 'IDC_VOICEOVER_BTN_RECORD', 'AXRole': 'AXButton'}
btn_record_stop = {'AXIdentifier': 'IDC_VOICEOVER_BTN_STOP', 'AXRole': 'AXButton'}
chx_mute_all_tracks_when_recording = {'AXIdentifier': 'IDC_VOICEOVER_BTN_MUTE_ALL', 'AXRole': 'AXCheckBox'}
btn_mixer = {'AXIdentifier': 'IDC_AUDIO_SETUP_BTN_MIXER', 'AXRole': 'AXButton'}
window_audio = {'AXTitle': 'Sound', 'AXRoleDescription': 'standard window', 'AXRole': 'AXWindow'}
btn_close_system_sound_setting = {'AXRole': 'AXButton', 'AXRoleDescription': 'close button'}
window_audio_setup = {'AXIdentifier': 'IDD_AUDIO_SETUP', 'AXRole': 'AXWindow'}
slider_audio_setup = {'AXIdentifier': 'IDC_AUDIO_SETUP_SLIDER_VOLUME', 'AXRole': 'AXSlider'}
menu_audio_device = {'AXIdentifier': 'IDC_AUDIO_SETUP_COMBOBOX_DEVICE', 'AXRole': 'AXButton'}
menu_audio_device_items = [menu_audio_device, {"AXRole": "AXStaticText", "get_all": True}]
cbx_timelimit_hour = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_COMBOBOX_HOUR', 'AXRoleDescription': 'button'}
cbx_timelimit_min = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_COMBOBOX_MINUTE', 'AXRoleDescription': 'button'}
cbx_timelimit_sec = {'AXIdentifier': 'IDC_VOICEOVER_OPTIONS_COMBOBOX_SECOND', 'AXRoleDescription': 'button'}
slider_audio_mixer = [{'AXIdentifier': 'IDD_LIBRARY'}, {'AXIdentifier': 'IDC_AUDIO_MIXER_SLIDER', 'AXRole': 'AXSlider'}]